name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
        
      - name: Install xcpretty
        run: gem install xcpretty
        
      - name: Build and Analyze
        run: |
          xcodebuild clean build analyze \
            -project Sunshade.xcodeproj \
            -scheme Sunshade \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            | xcpretty && exit ${PIPESTATUS[0]}
